apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka
spec:
  type: LoadBalancer
  clusterIP: 10.100.234.225
  selector:
    app: kafka
    id: "0"
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 32424
    name: kafka-port
    protocol: TCP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "32424"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "10.100.234.225"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.100.165.238:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1
        - name: ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "60000"
        - name: ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "60000"
  