---
version: '2'
services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    volumes: 
      - "~/Documents/dockerVolumes/zookeeper/data:/data"
      - "~/Documents/dockerVolumes/zookeeper/datalog:/datalog"
      - "~/Documents/dockerVolumes/zookeeper/logs:/logs"

  
  kafka-1:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zoo1

    ports:
      - 29092:29092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
      KAFKA_LISTENERS: ISSL://kafka-1:9092,OSSL://kafka-1:29092
      KAFKA_ADVERTISED_LISTENERS: ISSL://kafka-1:9092,OSSL://localhost:29092 
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ISSL:PLAINTEXT,OSSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: ISSL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: pw
      KAFKA_SSL_KEY_CREDENTIALS: pw
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: pw
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM : ""
    volumes: 
      - "~/Documents/dockerVolumes/kafka/secrets:/etc/kafka/secrets"
      - "~/Documents/dockerVolumes/kafka/data:/var/lib/kafka/data"
      